In [22]:
import numpy as np

In [24]:
B = np.array([[-0.21, -0.28, 0.05],
             [0.19, 0.01, -0.26],
             [0.39, -0.12, -0.06]])

In [25]:
g = np.array([-0.9, 3.8, -2.9])

In [27]:
q = np.linalg.norm(B, np.inf)

q

0.5700000000000001

In [30]:
# pp Lặp:
x0 = np.array([0, 2, -1])

for _ in range(3):
    x = B.dot(x0) + g
    ss = q / (1-q) * np.linalg.norm(x - x0, np.inf)
    x0 = x
    print(x, ss)

[-1.51  4.08 -3.08] 2.7572093023255824
[-1.8793  4.3547 -3.7937] 0.9460674418604657
[-1.914348  4.472842 -3.927869] 0.17785193023255758


In [32]:
# pp Seidel:
x = [0, 2, -1]
for _ in range(5):
    for i in range(3):
        x[i] = B[i].dot(x) + g[i]
    print(x)

[-1.5100000000000002, 3.7931, -3.8840719999999997]
[-1.8391716, 4.498347116, -3.92403425792]
[-1.969512869376, 4.49102493303776, -3.971590955545971]
[-1.9424688264589114, 4.508454820745137, -3.9602819634756337]
[-1.9524629944260488, 4.503789889770167, -3.964298436790041]
