In [18]:
import numpy as np

In [13]:
# Hệ chéo trội: output là B và g
A = [ [-15.4, 1, 6.3], 
      [-4.2, 16.8, 3.3],
      [-2.4, 5.3, 15.9] ]
b = [30, 25, -10]


m = lambda i, j: -A[i][j] / A[i][i] if i != j else 0
B = np.array( [[m(i, j) for j in range(len(b))] for i in range(len(b))])
g = [ b[i] / A[i][i] for i in range(len(b))]

In [19]:
B = np.array([[-0.21, -0.28, 0.05],
             [0.19, 0.01, -0.26],
             [0.39, -0.12, -0.06]])
g = [-0.9, 3.8, -2.9]

In [20]:
q = np.linalg.norm(B, np.inf)
q

0.5700000000000001

In [21]:
# Hệ lặp: Phương pháp lặp đơn:
x0 = [0 ,2, -1]
for _ in range(3):
    x = B.dot(x0) + g
    ss = (q * np.linalg.norm(x - x0, np.inf))/(1-q)
    x0 = x
    print(x, ss)

[-1.51  4.08 -3.08] 2.7572093023255824
[-1.8793  4.3547 -3.7937] 0.9460674418604658
[-1.914348  4.472842 -3.927869] 0.17785193023255758


In [22]:
# Hệ lặp: Phương pháp Seidel:
x = [0, 2, -1]
for _ in range(5):
    for i in range(len(x)):
        x[i] = B[i].dot(x) + g[i]
    print(x)

[-1.5100000000000002, 3.7931, -3.8840719999999997]
[-1.8391716, 4.498347116, -3.92403425792]
[-1.969512869376, 4.49102493303776, -3.971590955545971]
[-1.9424688264589114, 4.508454820745137, -3.9602819634756337]
[-1.9524629944260488, 4.503789889770167, -3.964298436790041]
