In [14]:
# Ví dụ 1: Phương trình vi phân cấp 1:

# from sympy import *
# h = 0.5
# imax = floor((1-0)/h)
# X = [0 + i*h for i in range(imax + 1)]

f = lambda x, y: y - x
X = [0, 0.1, 0.3, 0.5]
y = 2

for n in range(len(X) - 1):
    h = X[n+1] - X[n]
    k1 = h * f(X[n], y)
    k2 = h * f(X[n] + h/2, y + k1/2)
    k3 = h * f(X[n] + h/2, y + k2/2)
    k4 = h * f(X[n] + h, y + k3)

    y = y + (k1 + 2*k2 + 2*k3 + k4)/6
    print(y)

2.2051708333333333
2.649855655833333
3.148713698034833


In [7]:
# Ví dụ 2: Hệ phương trình vi phân cấp 1:
import numpy as np

f = lambda x, y: np.array([x * y[0] - y[1], y[0] + y[1] - 1])
X = [1, 1.1, 1.3, 1.5]
y = [-1, 2]

for n in range(len(X) - 1):
    h = X[n+1] - X[n]
    k1 = h * f(X[n], y)
    k2 = h * f(X[n] + h/2, y + k1/2)
    k3 = h * f(X[n] + h/2, y + k2/2)
    k4 = h * f(X[n] + h, y + k3)

    y = y + (k1 + 2*k2 + 2*k3 + k4)/6
    print(y)

[-1.32121997  1.98377289]
[-2.11619361  1.82819918]
[-3.18560532  1.43462193]


In [6]:
# Ví dụ 3: Phương trình vi phân cấp cao:
import numpy as np

f = lambda x, y: np.array([y[1], y[2], x * y[2] - y[0]])
X = [-1, -0.8, -0.6, -0.5]
y = [1, 0, -2]

for n in range(len(X) - 1):
    h = X[n+1] - X[n]
    k1 = h * f(X[n], y)
    k2 = h * f(X[n] + h/2, y + k1/2)
    k3 = h * f(X[n] + h/2, y + k2/2)
    k4 = h * f(X[n] + h, y + k3)

    y = y + (k1 + 2*k2 + 2*k3 + k4)/6
    print(y)

[ 0.96114    -0.38355933 -1.85169253]
[ 0.84796575 -0.74572765 -1.78005173]
[ 0.76452459 -0.92281499 -1.76341184]
