In [5]:
# Ví dụ 1: Phương trình vi phân cấp 1:
f = lambda x, y : y - x
X = [0, 0.1, 0.3, 0.5]
y = 2

for n in range(len(X) - 1):
    h = X[n+1] - X[n]
    y = y + h * f(X[n], y)
    print(y)

2.2
2.62
3.084


In [9]:
# Ví dụ 2: Hệ phương trình vi phân cấp 1:
import numpy as np

f = lambda x, y : np.array([x * y[0] - y[1], y[0] + y[1] - 1])
X = [1, 1.1, 1.3, 1.5]
y = [-1, 2]

for n in range(len(X) - 1):
    h = X[n+1] - X[n]
    y = y + h * f(X[n], y)
    print(y)

[-1.3  2. ]
[-1.986  1.94 ]
[-2.89036  1.7308 ]


In [8]:
# Ví dụ 3: Phương trình vi phân cấp cao
import numpy as np

f = lambda x, y : np.array([y[1], y[2], x * y[2] - y[0]])
X = [-1, -0.8, -0.6, -0.5]
y = [1, 0, -2]

for n in range(len(X) - 1):
    h = X[n+1] - X[n]
    y = y + h * f(X[n], y)
    print(y)

[ 1.  -0.4 -1.8]
[ 0.92  -0.76  -1.712]
[ 0.844   -0.9312  -1.70128]
